[project_name]
data = 'cppad_mixed'

[directory]
project_directory = '.'
rst_directory     = 'build/rst'
html_directory    = 'build/html'
tex_directory     = 'build/tex'

[root_file]
default = 'cppad_mixed.xrst'
dev     = 'xrst/devel.xrst'

[include_all]
rst_epilog = ''
rst_prolog = '''
.. |space| unicode:: 0xA0
.. |tab| replace:: |space| |space| |space|
'''
latex_macro = [
   '\newcommand{\B}[1]{ {\bf #1} }' ,
   '\newcommand{\R}[1]{ {\rm #1} }' ,
   '\newcommand{\W}[1]{ \; #1 \; }'
]

# BEGIN_SORT_THIS_LINE_PLUS_3
[project_dictionary]
data = [ '''
   bool
   cholesky
   cholmod
   cmake
   col
   const
   cpp
   cppad
   eigen
   eval
   factorization
   gsl
   hes
   init
   ipopt
   jac
   lagrangian
   laplace
   ldlt
   max
   obj
   ok
   rc
   rcv
   sh
   sparsity
   std
   taylor
   th
   val
   vec
   xam
''' ]
# END_SORT_THIS_LINE_MINUS_2
